# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  yarn_packages:
    working_directory: ~/repo
    docker:
      - image: circleci/node:9.7.1
    steps:
      - checkout
      # Cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:9.7.1

    steps:
      - run: yarn test
      - run: echo "Test Successful"
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:9.7.1
    steps:
      - run: |
           if [[ "${CIRCLE_BRANCH}"] == "develop"]]; then
             yarn build;
           elif [[ "${CIRCLE_BRANCH}"] == "develop"]]; then
             yarn build --production;
           fi
      - run:
        name: Echo Build Type
        command: echo "${CIRCLE_BRANCH}"
