version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.9.2
    steps:

      - run: echo $CIRCLE_BRANCH
      - checkout
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: ssh -T git@github.com

      # submodule repo initialize
      - run: git submodule init
      - run: git submodule update


      # install block
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is
      - run: yarn
      - save_cache:
                paths:
                  - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

      # test first before attempting to deploy
      - run: yarn test
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - run: aws s3 ls
      - run: yarn run deploy