version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9.2
    steps:
      - checkout
      - yarn
      - yarn test
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.9.2
    steps:
      - run: echo $CIRCLE_BRANCH
      # Clone docker repo, always master
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
#      - run: ssh -T git@github.com
      - run: git clone git@github.com:Humanyze/client-docker.git .
      # todo add branch context
      - run: git clone git@github.com:Humanyze/dashboard.git ./ember-dashboard
      - run: git clone --recursive git@github.com:Humanyze/elements-dashboard-react.git ./deployment-dashboard

      - setup_remote_docker
      - run: pwd
      - run: docker-compose build
      - run: echo $CIRCLE_BRANCH

#  deploy:

#workflows:
#  version: 2
#  test_build_deploy:
#    - test
#    - build
#    # sends notif to repull to server
#    - deploy



#$ {CIRCLE_BRANCH}
# docker login -u $DOCKER_USER -p $DOCKER_PASS