version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9.2
    steps:
      - checkout
      - yarn
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.9.2
    steps:
      # Clone docker repo, always master
      - run: git clone https://github.com/Humanyze/client-docker.git
      - setup_remote_docker
      - run: pwd
      - run: bash ./clonerepos.sh
      - run: echo $CIRCLE_BRANCH

  deploy:

workflows:
  version: 2
  test_build_deploy:
    - test
    - build
    # sends notif to repull to server
    - deploy



#$ {CIRCLE_BRANCH}
# docker login -u $DOCKER_USER -p $DOCKER_PASS